default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("POSTGRES_DATABASE") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>

development:
  <<: *default

test:
  <<: *default
  database: test

production:
  primary: &primary_production
    <<: *default
  cache:
    <<: *primary_production
    database: api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: api_production_queue
    migrations_paths: db/queue_migrate
